version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb
    ports:
      - 5435:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/test/data
volumes:
  dbdata:
    driver: local